name: Build and Release
on:
    push:
        tags:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
			- name: Setup Bun Runtime
  				uses: antongolub/action-setup-bun@v1 # or @v1.x.x
            - name: Build
              id: build
              run: |
                  bun install
                  bun run build
				  bun run binary
            # Create the release on github
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: ${{  github.ref_name }}
                  tag_name: ${{ github.ref }}
                  files: |
                      main.js
                      manifest.json
                      styles.css
					  server
